{ inputs, ... }:
{
  imports = [
    inputs.disko.nixosModules.default
    inputs.home-manager.nixosModules.default
    inputs.niri-nix.nixosModules.default
    inputs.stylix.nixosModules.default
    ./boot
    ./disko
    ./docs
    ./environment
    ./fonts
    ./hardware
    ./home-manager
    ./i18n
    ./networking
    ./nix
    ./nixpkgs
    ./packages
    ./programs
    ./security
    ./services
    ./stylix
    ./system
    ./systemd
    ./time
    ./users
    ./virtualisation
  ];
}
