{ inputs, ... }:
{
  imports = [
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager
    inputs.niri.nixosModules.niri
    inputs.sops-nix.nixosModules.sops
    inputs.stylix.nixosModules.stylix
    ./boot
    ./disko
    ./docs
    ./environment
    ./fonts
    ./hardware
    ./home-manager
    ./i18n
    ./networking
    ./nix
    ./nixpkgs
    ./packages
    ./programs
    ./secrets
    ./security
    ./services
    ./stylix
    ./system
    ./systemd
    ./time
    ./users
    ./virtualisation
  ];
}
