{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./bottom.nix
    ./brave.nix
    ./btop.nix
    ./bun.nix
    ./cava.nix
    ./chromium.nix
    ./clock-rs.nix
    ./eza.nix
    ./fastfetch.nix
    ./fish.nix
    ./fzf.nix
    ./gcc.nix
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./go.nix
    ./gpg.nix
    ./helix.nix
    ./home-manager.nix
    ./htop.nix
    ./imv.nix
    ./kitty.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./mpv.nix
    ./nh.nix
    ./npm.nix
    ./obs-studio.nix
    ./oh-my-posh.nix
    ./opencode.nix
    ./ripgrep.nix
    ./rust.nix
    ./skim.nix
    ./starship.nix
    ./uv.nix
    ./vscode.nix
    ./yazi.nix
    ./zathura.nix
    ./zig.nix
    ./zoxide.nix
  ];
}
