{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./btop.nix
    ./bun.nix
    ./cava.nix
    ./cavalier.nix
    ./chromium.nix
    ./clock-rs.nix
    ./eza.nix
    ./fastfetch.nix
    ./firefox.nix
    ./fish.nix
    ./fzf.nix
    ./ghostty.nix
    ./git.nix
    ./go.nix
    ./gpg.nix
    ./helix.nix
    ./home-manager.nix
    ./htop.nix
    ./imv.nix
    ./kitty.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./mpv.nix
    ./nh.nix
    ./obs-studio.nix
    ./oh-my-posh.nix
    ./rustlang.nix
    ./spicetify.nix
    ./starship.nix
    ./uv.nix
    ./vesktop.nix
    ./vscode.nix
    ./yazi.nix
    ./zathura.nix
    ./zed-editor.nix
    ./zoxide.nix
  ];
}
